version: '3'

services:
  ddns-server:
    build: ./docker
    container_name: ddns-server
    env_file:
      - ddns.env
    volumes:
      - ./conf:/ddns
    ports:
      - "2222:22"
      - "53:53"

