version: '3'

services:
  ddns-server:
    build: ./docker
    container_name: ddns-server
    env_file:
      - ddns.env
    volumes:
      # Public key used to authenticate to the server
      - ./conf/ssh.key.pub:/ddns/ssh.key.pub
    ports:
      - "2222:22"
      - "53:53"

