version: '3'

services:
  ddns-server:
    build: ./docker
    container_name: ddns-server
    restart: unless-stopped
    env_file:
      - ddns.env
    volumes:
      - ./conf:/ddns
    ports:
      - "2222:22"
        #- "53:53/tcp"
        #- "53:53/udp"

