version: '3'

services:
  ddns-agent:
    build: ./docker
    container_name: ddns-agent
    # Uncomment to force a DDNS update
    # Even if the address has not changed
    #command: force
    environment:
      # TODO: Adjust host and port as needed
      # Should point to the server
      - SSH_HOST=10.10.10.10
      - SSH_PORT=2222
    volumes:
      - ./conf:/ddns

