version: '3'

services:
  ddns-agent:
    build: ./docker
    container_name: ddns-agent
    # Uncomment to force a specific IP
    #command: 100.100.100.100
    env_file:
      - ddns.env
    volumes:
      - ./conf:/ddns

