version: '3'

services:
  ddns-agent:
    build: ./docker
    container_name: ddns-agent
    # Uncomment to force a DDNS update
    # Even if the address has not changed
    #command: force
    env_file:
      - ddns.env
    volumes:
      - ./conf:/ddns

